spring.application.name=CarHelper

server.port=

# mySQL database
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.jpa.database-platform=
spring.jpa.open-in-view=

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI keys
ai.api.key=
ai.model=

groq.api.key=
groq.model=

deepseek.api.key=
deepseek.model=

text.ai.provider=