package com.carhelper.adapter;

import com.carhelper.model.DiagnosticReport;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ApiAdapter implements AiResponseAdapter {

    private final ObjectMapper mapper = new ObjectMapper();

    @Override
    public DiagnosticReport translateResponse(String rawAiResponse) {
        if (rawAiResponse == null || rawAiResponse.isBlank()) {
            return buildFallbackReport("No AI response was received.");
        }

        try {
            String aiText = extractAiTextSafely(rawAiResponse);
            return buildReportFromAiText(aiText);
        } catch (Exception e) {
            return buildFallbackReport(rawAiResponse);
        }
    }

    private String extractAiTextSafely(String rawAiResponse) {
        String trimmed = rawAiResponse.trim();
        if (!looksLikeJson(trimmed)) {
            return trimmed;
        }

        try {
            JsonNode rootNode = mapper.readTree(trimmed);
            JsonNode geminiTextNode = rootNode.path("candidates").path(0).path("content").path("parts").path(0).path("text");
            if (!geminiTextNode.isMissingNode() && !geminiTextNode.asText().isBlank()) {
                return geminiTextNode.asText().trim();
            }
            JsonNode groqTextNode = rootNode.path("choices").path(0).path("message").path("content");
            if (!groqTextNode.isMissingNode() && !groqTextNode.asText().isBlank()) {
                return groqTextNode.asText().trim();
            }
            return trimmed;
        } catch (Exception e) {
            return trimmed;
        }
    }

    private DiagnosticReport buildReportFromAiText(String text) {
        if (text == null || text.isBlank()) {
            return buildFallbackReport("No readable AI report was found.");
        }

        String cleaned = cleanJsonText(text);
        if (looksLikeJson(cleaned)) {
            try {
                JsonNode json = mapper.readTree(cleaned);
                return new DiagnosticReport(readField(json, "issueName"), readField(json, "detectedProblems"), readField(json, "repairSuggestion"), readField(json, "estimatedCost"), readField(json, "aiDisclaimer"));
            } catch (Exception ignored) {
                return buildFallbackReport(text);
            }
        }
        return buildFallbackReport(text);
    }

    private DiagnosticReport buildFallbackReport(String text) {
        return new DiagnosticReport("AI Report", text, "", "", "This report was generated by AI and should be checked by a professional mechanic.");
    }

    private String readField(JsonNode json, String fieldName) {
        JsonNode field = json.path(fieldName);
        if (field.isMissingNode() || field.isNull()) {
            return "";
        }
        if (field.isArray()) {
            List<String> values = new ArrayList<>();
            for (int i = 0; i < field.size(); i++) {
                String value = field.get(i).asText();
                if (value != null && !value.isBlank()) {
                    values.add((i + 1) + ". " + value);
                }
            }
            return String.join("\n", values);
        }
        if (field.isObject()) {
            return field.toPrettyString();
        }
        return field.asText();
    }

    private String cleanJsonText(String text) {
        String cleaned = text.trim();
        if (cleaned.startsWith("```json")) {
            cleaned = cleaned.substring(7).trim();
        }
        if (cleaned.startsWith("```")) {
            cleaned = cleaned.substring(3).trim();
        }
        if (cleaned.endsWith("```")) {
            cleaned = cleaned.substring(0, cleaned.length() - 3).trim();
        }
        int firstBrace = cleaned.indexOf("{");
        int lastBrace = cleaned.lastIndexOf("}");
        if (firstBrace >= 0 && lastBrace > firstBrace) {
            cleaned = cleaned.substring(firstBrace, lastBrace + 1).trim();
        }
        return cleaned;
    }

    private boolean looksLikeJson(String text) {
        if (text == null) {
            return false;
        }
        String trimmed = text.trim();
        return (trimmed.startsWith("{") && trimmed.endsWith("}")) || (trimmed.startsWith("[") && trimmed.endsWith("]"));
    }
}
